[project]
name = "upwork-jobs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "black>=24.10.0",
    "isort>=5.13.2",
    "pylint>=3.3.3",
    "pythion>=1.0.22",
]
